// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addChirp = `-- name: AddChirp :one
INSERT INTO chirps (body, user_id)
    VALUES ($1, $2)
RETURNING
    id, created_at, updated_at, body, user_id
`

type AddChirpParams struct {
	Body   string    `json:"body"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddChirp(ctx context.Context, arg AddChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, addChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteChirp = `-- name: DeleteChirp :exec
DELETE FROM chirps
WHERE id = $1
`

func (q *Queries) DeleteChirp(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChirp, id)
	return err
}

const getAllChirpsASC = `-- name: GetAllChirpsASC :many
SELECT
    id, created_at, updated_at, body, user_id
FROM
    chirps
WHERE ($1::UUID IS NULL
    OR user_id = $1::UUID)
ORDER BY
    created_at ASC
`

func (q *Queries) GetAllChirpsASC(ctx context.Context, authorID uuid.NullUUID) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirpsASC, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllChirpsDESC = `-- name: GetAllChirpsDESC :many
SELECT
    id, created_at, updated_at, body, user_id
FROM
    chirps
WHERE ($1::UUID IS NULL
    OR user_id = $1::UUID)
ORDER BY
    created_at DESC
`

func (q *Queries) GetAllChirpsDESC(ctx context.Context, authorID uuid.NullUUID) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirpsDESC, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChirp = `-- name: GetChirp :one
SELECT
    id, created_at, updated_at, body, user_id
FROM
    chirps
WHERE
    id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
